version: 0.2
  pre_build:
    commands:
     - echo "Running pre-build steps"
  build:
    commands:
     - echo "Building the project with Maven"
     - mvn clean install
     - docker build -t test-poc .
  post_build:
    commands:
     - echo "Post-build steps"
     - echo "Build completed!"
artifacts:
  files:
    - target/*.jar   
  discard-paths: yes
